# -*- coding: utf-8 -*-
"""Watermark-open_cv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ue0WQQmViAGwM4lGQOix74HTD9tYjW_S
"""

import cv2 as cv
import numpy as np
from PIL import Image

img=Image.open('/tree.jpg')
img=img.resize((500,300))
img

logo=Image.open('/logo.jfif')
logo=logo.resize((100,50))
logo

img=np.array(img.convert('RGB'))
h_img,w_img,_=img.shape
logo=np.array(logo.convert('RGB'))
logo_h,logo_w,_=logo.shape

centre_y=int(h_img//2)
centre_x=int(w_img//2)
top_y=centre_y-int(logo_h//2)
left_x=centre_x-int(logo_w//2)
bottom_y=top_y+logo_h
right_y=left_x+logo_w

cv.putText(img,text="KING",org=(w_img-95,h_img-10),fontFace=cv.FONT_HERSHEY_COMPLEX,fontScale=0.5,color=(230,0,255),thickness=2,
           lineType=cv.LINE_4);

roi=img[top_y:bottom_y,left_x:right_y]
result=cv.addWeighted(roi,0,logo,1,0)

img[top_y:bottom_y,left_x:right_y]=result

cv.line(img,(0,centre_y),(left_x,centre_y),(0,0,255),1)
cv.line(img,(right_y,centre_y),(w_img,centre_y),(0,0,255),1)

img=Image.fromarray(img,'RGB')

img 
